version: '3.8'

# Services
services:
    ## InfluxDB - For sensor data
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: unless-stopped
        ports:
            - "8086:8086"
        volumes:
            - influxdb:/var/lib/influxdb
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
            - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
            - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}
            - DOCKER_INFLUXDB_INIT_DB=${INFLUXDB_DB}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.influxdb.rule=Host(`influxdb.metrics.meteo-airport.localhost`)"
            - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
            interval: 30s
            timeout: 10s
            retries: 5


    ## Mosquitto - For MQTT broker
    mosquitto:
        build:
            context: ./build/mosquitto
            dockerfile: Dockerfile
            args:
                - MQTT_USER=${MQTT_USER}
                - MQTT_PASSWORD=${MQTT_PASSWORD}
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883"
            - "9001:9001"
            - "8883:8883"
        volumes:
            - ./mosquitto/config:/etc/mosquitto
        healthcheck:
            test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "test"]
            interval: 30s
            timeout: 10s
            retries: 5
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mosquitto.rule=Host(`mqtt.meteo-airport.localhost`)"
            - "traefik.http.services.mosquitto.loadbalancer.server.port=9001"

    # MQTTX - For MQTT Web Client
    mqtt-web-client:
        image: emqx/mqttx-web
        container_name: mqtt-web-client
        restart: unless-stopped
        ports:
            - "81:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mqtt-web-client.rule=Host(`mqttx.meteo-airport.localhost`)"
            - "traefik.http.services.mqtt-web-client.loadbalancer.server.port=80"

    ## Reverse Proxy - For accessing each service by subdomain
    reverse-proxy:
        container_name: reverse-proxy
        build:
            context: ./build/traefik
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

# Volumes
volumes:
    influxdb: