sensor:
  airport_id: "CDG"
  sensor_id: 1
  topic: "airport/CDG/temperature"
  unit: "Celsius"
  time_format: "2006-01-02T15:04:05Z07:00"

broker:
  client:
    protocol: "tcp"
    host: "localhost"
    port: 1883
    username: "admin"
    password: "anotherSecretPassword"
  publish_topic: "airport/CDG/temperature"