storages:
  temperature:
    influxdb:
      url: "http://localhost:8086"
      token: "Y0v8Bxv9ZsiA1LZh0bPcfe1Tploz84mM8T4aRU154nETyRabwfPM6T-4ciBY3zS5CiQrtcCAjZ9QTAv1BrG0aA=="
      bucket: "metrics"
      organization: "meteo-airport"
    csv:
      path_directory: "/path/to/directory"
      time_format: "2006-01-02T15:04:05Z07:00"

  humidity:
    influxdb:
      url: "http://localhost:8086"
      token: "Y0v8Bxv9ZsiA1LZh0bPcfe1Tploz84mM8T4aRU154nETyRabwfPM6T-4ciBY3zS5CiQrtcCAjZ9QTAv1BrG0aA=="
      bucket: "metrics"
      organization: "meteo-airport"
    csv:
      path_directory: "/path/to/directory"
      time_format: "2006-01-02T15:04:05Z07:00"


mqtt:
  protocol: "tcp"
  host: "localhost"
  port: 1883
  username: "admin"
  password: "anotherSecretPassword"