broker:
  protocol: "tls"
  host: "0d23650ad8334e8b96e162999382b62d.s2.eu.hivemq.cloud"
  port: 8883
  username: "arduino"
  password: "not4nArduino"
  client_id: "temperature-sensor-CDG-1"

sensors_alert:
  windSpeed:
    incoming_topic: "airport/CDG/wind"
    outgoing_topic: "alerts/airport/CDG/wind"
    lower_bound: 20
    higher_bound: 30
    incoming_qos: 1
    outgoing_qos: 1
    client_id: "alert-wind-sensor-CDG-1"
