settings:
  temperature:
    influxdb:
      url: "http://localhost:8086"
      token: "9o53z0vBFzgb1w9f-icJgdg8gOltOTY9AwpXaUeimPxbiJ2md5ys32K1hTWf82ZV03oMFL2XM_PL3sXjhs1rRg=="
      bucket: "metrics"
      organization: "meteo-airport"
    csv:
      path_directory: "./data"
      separator: ';'
      time_format: "2006-01-02T15:04:05Z07:00"
    qos: 0

  humidity:
    influxdb:
      url: "http://localhost:8086"
      token: "9o53z0vBFzgb1w9f-icJgdg8gOltOTY9AwpXaUeimPxbiJ2md5ys32K1hTWf82ZV03oMFL2XM_PL3sXjhs1rRg=="
      bucket: "metrics"
      organization: "meteo-airport"
    qos: 0

mqtt:
  protocol: "tcp"
  host: "localhost"
  port: 1883
  username: "admin"
  password: "anotherSecretPassword"
  client_id: "storage-manager-weather-sensors-2"