sensor:
  airport_id: "CDG"
  sensor_id: 1
  topic: "airport/CDG/temperature"
  type: "temperature"
  unit: "Celsius"
  time_format: "2006-01-02T15:04:05Z07:00"

broker:
  client:
    protocol: "tls"
    host: "411d6c045163486b846c891f3910e83f.s2.eu.hivemq.cloud"
    port: 8883
    username: "arduino"
    password: "not4nArduino"
    client_id: "temperature-sensor-CDG-1"
  qos: 1