name: Lint Go Code

on:
    push:
        branches: [ main ]
    pull_request:

permissions:
    contents: read
    pull-requests: read
    checks: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        strategy:
            matrix:
                os: [ 'macos-latest', 'windows-latest' ]
        name: Lint
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Go
                uses: actions/setup-go@v3

                with:
                    go-version: 1.21

            -   name: Lint with golangci-lint
                uses: golangci/golangci-lint-action@v3
                with:
                    version: v1.54
                    args: --timeout=10m
