name: Lint Go Code

on:
    push:
        branches: [ main ]
    pull_request:

permissions:
    contents: read
    pull-requests: read
    checks: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Go
                uses: actions/setup-go@v4

                with:
                    go-version: 1.21
                    cache: false

            -   name: Lint with golangci-lint
                uses: golangci/golangci-lint-action@v3
                with:
                    version: v1.54
                    args: --timeout=10m
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: lint
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Go
                uses: actions/setup-go@v4

                with:
                    go-version: 1.21
                    cache: false

            -   name: Build with Go
                run: go build -v ./...
